"use client";

import { useRef } from "react";
import { getPaymentById } from "@/lib/mongoose/actions/paymentActions";
import { format } from "date-fns";
import html2pdf from "html2pdf.js";

export default async function ReceiptPage({ params }) {
  const payment = await getPaymentById(params.id);

  if (!payment) return <div className="p-6">Payment not found.</div>;

  const { tenant, lease, amount, method, type, paidAt, receiptNumber } =
    payment;

  const receiptRef = useRef(null);

  const downloadPDF = () => {
    const element = receiptRef.current;
    const opt = {
      margin: 0.5,
      filename: `${receiptNumber}.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
    };
    html2pdf().set(opt).from(element).save();
  };

  return (
    <div className="max-w-2xl mx-auto py-10 space-y-4 px-6">
      <div
        ref={receiptRef}
        className="border rounded-md bg-white p-6 print:bg-white"
      >
        <div className="flex justify-between items-center">
          <h1 className="text-xl font-bold">Payment Receipt</h1>
          <span className="text-xs text-muted-foreground">
            #{receiptNumber}
          </span>
        </div>

        <div className="border-t pt-4 space-y-2 text-sm">
          <p>
            <strong>Tenant:</strong> {tenant?.name}
          </p>
          <p>
            <strong>Property:</strong> {lease?.property?.name}
          </p>
          <p>
            <strong>Amount Paid:</strong> ZMW {amount.toLocaleString()}
          </p>
          <p>
            <strong>Type:</strong> {type}
          </p>
          <p>
            <strong>Method:</strong> {method}
          </p>
          <p>
            <strong>Date Paid:</strong> {format(new Date(paidAt), "PPPpp")}
          </p>
        </div>

        <div className="border-t pt-4 text-xs text-muted-foreground">
          <p>
            This receipt was generated by the system and may be used for proof
            of payment.
          </p>
        </div>
      </div>

      <div className="flex justify-end gap-2 print:hidden">
        <button
          onClick={() => window.print()}
          className="text-sm px-3 py-1 border rounded"
        >
          Print
        </button>
        <button
          onClick={downloadPDF}
          className="text-sm px-3 py-1 border rounded"
        >
          Download PDF
        </button>
      </div>
    </div>
  );
}
